import React, {useEffect, useState, useRef} from 'react';
import {Download, X, Share, WifiOff, RefreshCw, ArrowUpRight, Check} from 'lucide-react';
import {useRegisterSW} from 'virtual:pwa-register/react';
export default function InstallApp(){
 const sheet=useRef(null);
 const [prompt,setPrompt]=useState(null),[open,setOpen]=useState(false),[online,setOnline]=useState(navigator.onLine),[installed,setInstalled]=useState(matchMedia('(display-mode: standalone)').matches||navigator.standalone),[message,setMessage]=useState('');
 const {offlineReady:[ready],needRefresh:[refresh],updateServiceWorker}=useRegisterSW({onRegisterError(){setMessage('离线资源未能准备完成，请联网后刷新重试。')}});
 useEffect(()=>{function capture(e){e.preventDefault();setPrompt(e)}function done(){setInstalled(true);setPrompt(null);setMessage('已安装，可从手机桌面打开换换。')}function net(){setOnline(navigator.onLine)}
 addEventListener('beforeinstallprompt',capture);addEventListener('appinstalled',done);addEventListener('online',net);addEventListener('offline',net);
 return ()=>{removeEventListener('beforeinstallprompt',capture);removeEventListener('appinstalled',done);removeEventListener('online',net);removeEventListener('offline',net)}},[]);
 useEffect(()=>{if(!open)return;const previous=document.activeElement,overflow=document.body.style.overflow;document.body.style.overflow='hidden';sheet.current?.querySelector('button')?.focus();function key(e){if(e.key==='Escape')setOpen(false);if(e.key==='Tab'){const nodes=sheet.current?.querySelectorAll('button,a[href]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}addEventListener('keydown',key);return ()=>{removeEventListener('keydown',key);document.body.style.overflow=overflow;previous?.focus()}},[open]);
 async function install(){if(prompt){await prompt.prompt();const choice=await prompt.userChoice;setPrompt(null);setMessage(choice.outcome==='accepted'?'安装请求已提交，请查看浏览器提示。':'已取消安装，仍可继续使用网页版。')}else setOpen(true)}
 const ios=/iPad|iPhone|iPod/.test(navigator.userAgent);
 return <><div className="app-status-bar"><span>{!online?<><WifiOff size={14}/>离线模式 · 数据保存在本机</>:<><Check size={14}/>{installed?'已在独立 APP 模式运行':'换换 APP · 本机体验版'}</>}</span><button onClick={()=>setOpen(true)}><Download size={14}/>{installed?'应用信息':'安装到手机'}</button></div>
 {refresh&&<div className="app-update"><RefreshCw size={16}/><span>新版本已就绪，保存好当前表单后更新。</span><button onClick={()=>updateServiceWorker(true)}>更新应用</button></div>}
 {open&&<div className="install-backdrop" onClick={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section ref={sheet} className="install-sheet" role="dialog" aria-modal="true" aria-labelledby="install-title"><button autoFocus className="install-close" aria-label="关闭安装说明" onClick={()=>setOpen(false)}><X size={20}/></button><img src="/icons/icon-192.png" alt="换换应用图标"/><span className="section-kicker">YOUR NEXT FAVORITE, ONE SWAP AWAY</span><h2 id="install-title">把换换，装进口袋。</h2><p>从桌面一键打开，让闲置再次被喜欢。</p><div className="install-features"><span>独立窗口</span><span>本机保存</span><span>{ready?'离线资源已就绪':'联网后准备离线资源'}</span></div>{installed?<div className="install-help"><Check size={18}/><span>当前已在 APP 模式运行。</span></div>:prompt?<button className="button primary full" onClick={install}><Download size={17}/>安装换换 APP</button>:<div className="install-help"><Share size={20}/><div><strong>{ios?'在 Safari 中添加到主屏幕':'在手机浏览器中安装'}</strong><p>{ios?'点击 Safari 的“分享”按钮，选择“添加到主屏幕”，然后点击“添加”。':'用 Chrome 或 Edge 打开此页面，在浏览器菜单中选择“安装应用”或“添加到主屏幕”。'}</p><p>如果正在内嵌预览中，请先打开独立预览页面，再使用浏览器安装。</p></div></div>}<a className="install-open" href="/?install=1" target="_blank" rel="noopener noreferrer">在独立页面打开 <ArrowUpRight size={15}/></a>{message&&<p role="status">{message}</p>}<div className="install-disclaimer">v0.2 · 可安装网页应用（PWA），不是 APK。<br/>物品、聊天、交换与举报仅保存在当前浏览器，不会发送给真实用户。首次联网加载后可离线使用。清除浏览器数据会删除本机记录。</div></section></div>}
 </>;
}
